# Generated by Django 6.1 on 2026-08-17 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('degree', models.CharField(blank=True, max_length=150)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('graduation_year', models.CharField(blank=True, max_length=10)),
                ('current_job_title', models.CharField(blank=True, max_length=150)),
                ('years_of_experience', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('preferred_job_role', models.CharField(blank=True, max_length=150)),
                ('preferred_work_location', models.CharField(blank=True, max_length=150)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
